blank_issues_enabled: true

contact_links:

  - name: Help
    about: The issue tracker is used for reporting bugs, not asking for help. Ask for help in the Discord server!
    url: x

  - name: Suggestion
    about: Have an idea or a suggestion? Create a discussion.
    url: x
