name: Bug Report
description: Found a bug? Report it so we can fix it as soon as possible!
title: "core/{CORE_LIBRARY}: "
labels: bug

body:

  - type: textarea
    attributes:
      label: Description
      description: Describe the bug and how the behavior is unexpected
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduce
      description: Describe the steps to reproduce the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect the behavior should be
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code/Screenshots/Videos
      description: Share code or media that might help us debug the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Help us know your environment where you are experiencing the bug
    options:
      - label: I am using TypeScript
      - label: I have the `--unstable` command line flag enabled
    validations:
      required: true

  - type: textarea
    attributes:
      label: Keywords
      description: This is not required, but it is helpful for eliminating duplicates

    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
