name: Bug Report
description: Found a bug? Report it so we can fix it as soon as possible!
labels: bug

body:

  - type: textarea
    attributes:
      label: Description
      description: Describe the bug and how the behavior is unexpected.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduce
      description: Describe the steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect the behavior should be.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code/Screenshots/Videos
      description: Share code or media that might help us debug the issue.
    validations:
      required: true

  - type: input
    attributes:
      label: Deno Version
    validations:
      required: true

  - type: input
    attributes:
      label: Platform
    validations:
      required: true

  - type: input
    attributes:
      label: Whirlybird Version
    validations:
      required: true

  - type: checkboxes
    attributes:
      options:
        - label: I am using TypeScript.
        - label: I have the `--unstable` command line flag enabled.

  - type: textarea
    attributes:
      label: Keywords
      description: This will help others find this issue in the search bar.
